### ISSUE TITLE
Error en el calculo de calorias

### ISSUE THREAD

**Issue by cesarenrique** [cesarenrique/DCAP2#1]
Cuando se ingresa una cantidad inferior a 60 minutos, la calculadora da valor cero consumo de calorías, cuando en realidad hay un mínimo consumo de calorías, hay personas que solo tienen rutinas de ejercicios de menos de una hora, debería facilitarse un consumo de calorías para ese grupo de personas.

**Comment by equipodedesarrollop2** [comment]
Saludos Cesar Enrique, gracias por colaborar con este enorme proyecto, si es verdad que eso ocurre, pero con que calculo de calorías te ocurre mas frecuentemente

**Comment by cesarenrique** [comment]
Me ocurre con todas las calorías de todas las opciones, como es una primeras versiones me imagino que será uno de los primeros fallos

**Comment by equipodedesarrollop2** [comment]
Vamos corregirlo para que las siguiente version soporte el consumo de esas calorías quemadas en menos de una hora.

**Comment by equipodedesarrollop2** [comment]
Se ha corregido el error, ahora se puede disfrutar del calculo de calorías de menos de 60 minutos.

**Comment by cesarenrique** [comment]
Creo que estoy bastante satisfecho con el resultado cierro, podéis cerrar la incidencia

**Comment by equipodedesarrollop2** [comment]
perfecto.
